import { Inter } from "next/font/google";
import "./globals.css";

import { UserContextProvider } from "./context/userContext";
import Header from "./components/Header";
import { CalendarContextProvider } from "./context/calendarContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body className={`${inter.className} h-screen p-1`}>
            <UserContextProvider>
               <CalendarContextProvider>
                  <Header />
                  {children}
               </CalendarContextProvider>
            </UserContextProvider>
         </body>
      </html>
   );
}
